"""Initial revision

Revision ID: 25bc5992cb40
Revises: f193c82750b3
Create Date: 2024-10-20 17:24:04.345019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bc5992cb40'
down_revision: Union[str, None] = 'f193c82750b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'Fname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'Lname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'Lname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'Fname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
